---
name: SlapperRotationV2
version: 2.0.3
main: xqwtxon\SlapperRotationV2\Main
api: 4.0.0
src-namespace-prefix: xqwtxon\SlapperRotationV2
depend: Slapper
author: xqwtxon
description: Slappers look at players!
...
