---
name: SlapperRotation
version: 1.0.5
main: ReinfyTeam\SlapperRotation\Main
api: 4.0.0
src-namespace-prefix: ReinfyTeam\SlapperRotation
depend: Slapper
author: ReinfyTeam
description: Slappers look at players!
...
