name: SlapperRotationV2
main: SlapperRotationV2\Main
src-namespace-prefix: SlapperRotationV2\
version: 2.0.1
api: [4.0.0]
depend: Slapper
author: xqwtxon
description: Slappers look at players!
