name: SlapperRotation
main: xqwtxon\SlapperRotation\Main
src-namespace-prefix: xqwtxon\SlapperRotation
version: 2.0.0
api: [4.0.0]
depend: Slapper
author: xqwtxon
description: Slappers look at players!