# SlapperRotationV2
# Here you can configure slapper what can do. 

# Max Distance Between Slapper to player.
max-distance: 8

# SlapperRotation should enabled?
enabled: true



# Config Version
# Please dont change/modify unless you know what you are doing!
config-version: "1.0.5"
